channels:
  - conda-forge
dependencies:
  - python>=3.8
  - configparser
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy
  - dask
  - cytoolz
  - python-rapidjson
  - gensim
  - matplotlib==3.7.1
  - seaborn
  - umap-learn
  - pyarrow
  - graphviz
  - pydot
  - xgboost
  - pillow
  - wordcloud
  - graph-tool
  - jupyter
  - gdal
  - geopandas
  - libpysal
  - mapclassify
  - statsmodels
  - networkx
  - spectra
  - descartes
  - scikit-learn
  - nltk
  - KDEpy
  - xlrd
  - contextily
  - pip:
    - pytz
    - ftfy
    - emoji
    - adjustText
    - toml
    - scattertext
    - powerlaw
    - shifterator
    - git+https://github.com/zorzalerrante/scikit-fusion
    - git+https://github.com/zorzalerrante/aves
    - pymunk
    - emoji
    - bezier
    - matplotlib-scalebar
    - python-dotenv
    - tweepy
    - requests
    - aiohttp
    - pyahocorasick