channels:
  - conda-forge
dependencies:
  - python
  - configparser
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy<1.13
  - dask
  - cytoolz
  - python-rapidjson
  - gensim
  - matplotlib
  - seaborn
  - pyarrow
  - graphviz
  - pydot
  - xgboost
  - pillow
  - wordcloud
  - graph-tool
  - jupyter
  - networkx
  - scikit-learn
  - nltk
  - KDEpy
  - xlrd
  - plotly
  - pytz
  - pip:
    - ftfy
    - emoji
    - adjustText
    - toml
    - powerlaw
    - pymunk
    - emoji
    - bezier
    - python-dotenv
    - tweepy
    - requests
    - aiohttp
    - pyahocorasick