channels:
  - conda-forge
dependencies:
  - python
  - configparser
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy
  - dask
  - cytoolz
  - python-rapidjson
  - gensim
  - matplotlib
  - seaborn
  - pyarrow
  - graphviz
  - pydot
  - xgboost
  - pillow
  - wordcloud
  - graph-tool
  - jupyter
  - networkx
  - spectra
  - descartes
  - scikit-learn
  - nltk
  - KDEpy
  - xlrd
  - pip:
    - pytz
    - ftfy
    - emoji
    - adjustText
    - toml
    - scattertext
    - powerlaw
    - shifterator
    - pymunk
    - emoji
    - bezier
    - matplotlib-scalebar
    - python-dotenv
    - tweepy
    - requests
    - aiohttp
    - pyahocorasick