[rm]
title = 'Región Metropolitana'
undisclosed_title = 'Sin Región Explícita'
threshold = 0.7
REGION_ID = 13

[rm.location]
patterns = [
    'barrio yungay',
    'barrio franklin',
    'barrio matta',
    'barrio italia',
    'barrio lastarria',
    'barrio san isidro',
    'lastarria',
    'buin',
    'paine',
    'el monte',
    'cerrillos',
    'cerro navia',
    'chicureo',
    'isla de maipo',
    'colina',
    'conchali',
    'conchalí',
    '^el bosque',
    'lampa',
    'melipilla',
    'est\. central',
    'estacion central',
    'estación central',
    'huechuraba',
    'independencia',
    'la cisterna',
    'la granja',
    'la florida',
    'la pintana',
    'la reina',
    'las condes',
    'lo barnechea',
    'lo espejo',
    'lo prado',
    'macul',
    'maipu',
    'maipú',
    'pedro aguirre cerda',
    'peñalolen|peñalolén|penalolen',
    'pirque',
    'providencia',
    'pudahuel',
    'puente alto|pte\.?\s?alto',
    'quilicura',
    'quinta normal',
    'recoleta',
    'renca',
    'san bernardo',
    'villa francia',
    'san miguel',
    'san joaquín',
    'san joaquin',
    'san ramón',
    'vitacura',
    'ñuñoa|nunoa|ñuñohue|nunohue|ñuñork|nunork',
    'santiago centro',
    'cajon del maipo',
    'santiago centro|stgo\.? centro',
    'santiago|santiasco|[\W]+scl?$|stgo|^SCL$|^SCL .*$',
    'region metropolitana',
    'región metropolitana',
    'talagante',
    'curacavi',
    'curacaví',
    'san jose de maipo',
    'san josé de maipo',
    'san ramon',
    'san ramón',
    'peñaflor|penaflor',
    'padre hurtado',
    'malloco',
    'maria pinto',
    'maría pinto',
    'san carlos de apoquindo',
    'til\s?til',
    'calera de tango',
]

[rm.description_token]
must_have = ['santiaguino', 'santiaguina', 'talagante', 'peñaflor', 'melipilla']

[rm.tweet_tokens]
must_have = []

[loslagos]
title = 'Región de Los Lagos'
REGION_ID = 10

[loslagos.location]
patterns = [
    'chaiten',
    'chaitén',
    'castro',
    'chiloe',
    'chiloé',
    'puerto\s?montt|pto[.]?\s?montt',
    'puerto\s?varas|pto[.]?\s?varas',
    'osorno',
    'futaleufu',
    'ancud',
    'los lagos',
    'region de los lagos',
    'región de los lagos',
    'quellon',
    'quellón',
    'calbuco',
    'llanquihue',
    'frutillar',
    'purranque',
    'maullin, chile',
    'maullín, chile',
    'dalcahue',
    'fresia, chile',
    'hornopiren',
    'maillen',
]

[loslagos.description_token]
must_have = [
    'chilote',
    'chilota',
    'montt',
    'osorno',
    'varas',
    'ancud',
    '#chiloé',
    'chiloé',
    'osornino',
    'osornina',
    'lagos',
]

[loslagos.tweet_tokens]
must_have = ['@australosorno', '@defendamschiloe', '@radiosago']

[loslagos.domain]
must_have = ['reloncaviradio.cl', 'radiosago.cl']

[biobio]
title = 'Región del Bío Bío'
REGION_ID = 8

[biobio.location]
patterns = [
    'lebu',
    'talcahuano',
    'cañete|canete',
    'concepcion|concepción|^conce[\W]|^conce$|^ccp$',
    '(?:^|\s|\W)penco(?:$|\s|\W)',
    'dichato',
    'mulchen',
    'bio\W?bio',
    'hualpen',
    'los alamos, chile',
    'chiguayante',
    'arauco',
    'laraquete',
    'coronel, chile',
    '(?:^|\s|\W)tome(?:$|\s|\W)',
    '(?:^|\s|\W)tomé(?:$|\s|\W)',
    'curanilahue',
    'los angeles\W+chile',
    'tucapel',
    'huipil|huepil',
    'san carlos\W+chile',
    'san pedro de la paz\W+chile',
    'nacimiento\W+chile',
    'cabrero\W+chile',
    'laja\W+chile',
    'yumbel',
    'lota\W+chile',
    'hualqui',
    'santa barbara, chile',
    'quirihue',
    'bulnes, chile',
    'canete, chile',
]

[biobio.description_token]
must_have = [
    'concepción',
    'penquista',
    'udec',
    '#udec',
    'talcahuano',
    'ucsc',
    'ccp',
    'biobío',
]

[biobio.tweet_tokens]
must_have = []

[biobio.account_ids]
known_users = [
    1219821715997499392, # JRechazobiobio
    4060622956,          # anatrapbiobio
    1108144807602520064, # biobio_region
]

[araucania]
title = 'Región de la Araucanía'
REGION_ID = 9

[araucania.location]
patterns = [
    'puren',
    'collipulli',
    'pucon',
    'pucón',
    'temuco',
    'wallmapu',
    'araucania',
    'araucanía',
    'villarr?ica',
    'ix region',
    'ix región',
    'carahue',
    'tolten',
    'toltén',
    'melipeuco',
    '(?:^|\W|\s)angol(?:$|\W|\s)',
    'padre las casas\W+chile',
    'loncoche',
    'nueva imperial\W+chile',
    'pitrufquen',
    'curacautin',
    'curacautín',
    'lautaro',
    'traiguen',
    'traiguén',
    'victoria, chile',
    'gorbea, chile',
]

[araucania.description_token]
must_have = ['temucano', 'temucana', 'temuco', 'ufro', 'wallmapu', 'temuquense']


[araucania.tweet_tokens]
must_have = ['@radiokurruf', '@rnearaucania']

[araucania.account_ids]
known_users = [
    1301272724455723008, # udi_araucania
    3377432242,          # anefaraucania
    737822669991759872,  # jppd_araucania
]

[valparaiso]
title = 'Región de Valparaíso'
REGION_ID = 5

[valparaiso.location]
patterns = [
    'san felipe',
    'algarrobo',
    'el quisco',
    'la ligua',
    'putaendo',
    'papudo',
    'valpo',
    'con-?con',
    'con-?cón',
    'concón',
    'quilpue',
    'quilpué',
    'olmue',
    'olmué',
    'quintero',
    'villa alemana',
    'curauma',
    'puchuncavi',
    'puchuncaví',
    'san antonio, chile',
    'llay llay|llaillai|llayllay|llaillay',
    'quillota',
    'zapallar',
    'robinson crusoe',
    'v region|quinta region',
    'v región|quinta región',
    '^viña$|viña del mar|reñaca',
    'valparaiso',
    'valparaíso',
    'los andes',
    'el tabo',
    'isla negra',
    'cartagena, chile',
    'santo domingo\W+chile',
    'la calera\W+chile',
    'casablanca\W+chile',
    'cabildo\W+chile',
    'hijuelas\W+chile',
    'limache',
    'juan fernandez',
    'juan fernández',
    'Isla de Pascua|easter island|hanga roa',
    'monte patria, chile',
    'marga\W?marga',
    'san esteban, chile',
    'catemu',
    'nogales, chile',
    'santa maria, chile',
    'santa maría, chile',
]

[valparaiso.description_token]
must_have = [
    'porteño',
    'porteña',
    'valparaíso',
    'pucv',
    'wanderino',
    'wanderina',
    'uv',
    '#valparaíso',
    'viñamarino',
    'viñamarina',
    'wanderers',
    'valparaiso',
    'viña',
    'evertoniano',
    'evertoniana',
]

[valparaiso.tweet_tokens]
must_have = [
    '@elepicentro', 
    '@corporacionsw', 
    '@rnevalparaiso',
]

[valparaiso.domain]
must_have = ['diariolaquinta.cl']

[antofagasta]
title = 'Región de Antofagasta'
REGION_ID = 2

[antofagasta.location]
patterns = [
    'mejillones',
    'antofagasta|antofa',
    'calama',
    'san pedro de atacama',
    'tocopilla',
    'chacabuco',
    'chuquicamata',
    'alto del carmen',
    'tal\s?tal',
    'huasco',
]

[antofagasta.description_token]
must_have = [
    'antofagasta',
    'tocopilla',
    'antofagastino',
    'antofagastina',
    '#antofagasta',
    'calama',
    'ucn',
]


[antofagasta.tweet_tokens]
must_have = []

[antofagasta.account_ids]
known_users = [
    1567381195, # diariocalama
]

[antofagasta.domain]
must_have = ['diariocalama.cl', 'calamaenlinea.cl']

[maule]
title = 'Región del Maule'
REGION_ID = 7

[maule.location]
patterns = [
    'constitución, chile',
    'maule',
    'loncomilla',
    'linares',
    'curico',
    'curicó',
    '(?:^|\s|\W)talca(?:$|\s|\W)',
    'region del maule',
    'región del maule',
    'vii region',
    'vii región',
    'cauquenes',
    'parral',
    'molina\W+chile',
    'teno\W+chile',
    'colbun',
    'colbún',
    'longavi',
    'longaví',
    'san javier, chile',
    'curanipe',
    'san clemente, chile',
    'romeral',
    'villa alegre, chile',
]

[maule.user_name]
must_have = ['maule']

[maule.description_token]
must_have = [
    'talca',
    'maule',
    'talquino',
    'talquina',
    'linares',
    'curicano',
    'curicana',
    'curicó',
    'maulino',
    'maulina',
    '#linares',
    '#ubb',
    'ubb',
    '#talca',
    '@utalca',
    'linarense',
    'ranguerino',
    'ranguerina',
    'rangerino',
    'rangerina',
]

[maule.tweet_tokens]
must_have = ['@rne_maule_', '@redmaule']

[maule.domain]
must_have = ['septimapaginanoticias.cl']

[atacama]
title = 'Región de Atacama'
REGION_ID = 3

[atacama.location]
patterns = [
    'chañaral',
    '^atacama',
    'copiapo',
    'copiapó',
    'vallenar',
    'valle del huasco',
    'caldera\W+chile',
    'chanaral',
    'huasco\W+chile',
    'bahía inglesa',
]

[atacama.user_name]
must_have = ['atacama']

[atacama.description_token]
must_have = [
    'atacama',
    'atacameño',
    'atacameña',
    '#atacama',
    'copiapino',
    'copiapina',
    'copiapó',
    'copiapo',
]

[atacama.tweet_tokens]
must_have = ['@radiogennesis']

[atacama.domain]
must_have = ['tierramarillano.cl']

[atacama.account_ids]
known_users = [
    2670786799, # anef_atacama
]


[ohiggins]
title = "Región del Libertador General Bernardo O'Higgins"
REGION_ID = 6

[ohiggins.user_name]
must_have = ["o'higgins"]

[ohiggins.location]
patterns = [
    'san fernando',
    'pichidegua',
    "region de o'higgins",
    "región de o'higgins",
    'cachapoal',
    'peumo',
    'san vicente de tagua tagua|san vicente de tt|san vicente, chile',
    'rancagua',
    'machali',
    'machalí',
    'pichilemu',
    'chimbarongo',
    'vi region',
    'vi región',
    '(?:^|\s|\W)rengo(?:$|\s|\W)',
    'requinoa',
    'placilla',
    'santa cruz\W+chile',
    'graneros\W+chile',
    'nancagua',
    'donihue',
    'doñihue',
    'las cabras, chile',
    'codegua',
    'quinta de tilcoco',
]

[ohiggins.description_token]
must_have = [
    'rancagua',
    'machalí',
    'rancagüino',
    'rancagüina',
    "o'higgins",
    '#rancagua',
    'rancaguino',
    'rancaguina',
    'colchagua',
    'pichilemu',
    'ohiggins',
    'libertador',
]

[ohiggins.tweet_tokens]
must_have = ['@rancagua_dgt']

[ohiggins.domain]
must_have = ['elrancaguino.cl']


[coquimbo]
title = 'Región de Coquimbo'
REGION_ID = 4

[coquimbo.user_name]
must_have = ['coquimbo']

[coquimbo.location]
patterns = [
    'andacollo',
    'la serena',
    'ovalle',
    'coquimbo',
    'guanaqueros',
    'los vilos',
    'tongoy',
    'illapel',
    'cuarta region',
    'iv region',
    'cuarta región',
    'iv región',
    'vicuna\W+chile',
    'vicu}a\W+chile',
    'elqui',
    'salamanca, choapa|salamanca, chile',
    '(?:^|\s|\W)choapa(?:$|\s|\W)',
    'canela\W+chile',
    'combarbala',
    'combarbalá',
    'paihuano',
]

[coquimbo.description_token]
must_have = [
    'coquimbo',
    'serena',
    '#laserena',
    '#coquimbo',
    'illapel',
    '##illapel',
    'ovallina',
    'ovallino',
    'ovalle',
    'coquimbano',
    'coquimbana',
    'serenense',
]

[coquimbo.tweet_tokens]
must_have = ['@pccoquimbo', '@guayacanfmcl']

[coquimbo.account_ids]
known_users = [
    892254834,  # radiocoquimbo
    4858644809, # tvnredcoquimbo
]


[losrios]
title = 'Región de Los Ríos'
REGION_ID = 14

[losrios.location]
patterns = [
    '^la unión',
    'valdivia',
    'panguipulli',
    'region de los rios',
    'región de los ríos',
    'los rios\W+chile',
    'los ríos\W+chile',
    '(?:^|\s|\W)la union(?:$|\s|\W)',
    '(?:^|\s|\W)la unión(?:$|\s|\W)',
    'futrono',
    'lanco\W+chile',
    'isla teja',
    'rio bueno',
    'río bueno',
    'paillaco',
]

[losrios.profile_domain]
must_have = ['uach.cl']

[losrios.description_token]
must_have = [
    'valdiviano',
    'valdiviana',
    'valdivia',
    'uach',
    '#valdiviacl',
    'ríos',
    'ranco',
]

[losrios.tweet_tokens]
must_have = []


[aysen]
title = 'Región de Aysén'
REGION_ID = 11

[aysen.user_name]
must_have = ['aysén']

[aysen.location]
patterns = ['aysen', 'aysén', 'aisen', 'aisén', 'coyhaique', 'coihaique']

[aysen.description_token]
must_have = ['aysén', 'coyhaique', 'coyhaiquino', 'coyhaiquina']

[aysen.tweet_tokens]
must_have = []

[aysen.domain]
must_have = ['tehuelchenoticias.cl', 'eltirapiedras.cl']

[aysen.account_ids]
known_users = [
    1181662192040583173, # regionalaysen
]

[arica]
title = 'Región de Arica y Parinacota'
REGION_ID = 15

[arica.user_name]
must_have = ['arica']

[arica.location]
patterns = [
    'arica',
    'parinacota',
    'xv region',
    'xv región',
    'visviri',
    'putre',
    'camarones',
    'cuya',
]

[arica.description_token]
must_have = ['ariqueño', 'ariqueña', 'arica', 'parinacota', '#arica']

[arica.tweet_tokens]
must_have = []

[arica.account_ids]
known_users = [
    1244695782231609345, # diario_arica
]

[magallanes]
title = 'Región de Magallanes'
REGION_ID = 12

[magallanes.user_name]
must_have = ['magallanes']

[magallanes.location]
patterns = [
    'puerto williams',
    'punta arenas|magallanes|xii region|^puq|puq$|pta[.]? arenas',
    'tierra del fuego',
    'cape horn|cabo de hornos',
    'puerto natales|pto\.? natales',
    'natales\W+chile',
]

[magallanes.description_token]
must_have = [
    'magallanes',
    '#puq',
    '#puntaarenas',
    'arenas',
    'magallánico',
    'magallánica',
    'magallanica',
    'magallanico',
    'antártica',
    'natales',
    '#magallanes',
]

[magallanes.tweet_tokens]
must_have = ['@pinguinodiario']

[magallanes.domain]
must_have = ['laprensaaustral.cl', 'elpinguino.com']

[nuble]
title = 'Región de Ñuble'
REGION_ID = 16

[nuble.user_name]
must_have = ['ñuble']

[nuble.location]
patterns = [
    'chillan[\W]*',
    'chillán',
    'ñuble',
    'nuble',
    'quillon',
    'quillón',
    'niquen\W+chile',
    'coelemu',
    'yungay',
    'rucapequen',
    'rucapequén',
    'coihueco',
]

[nuble.description_token]
must_have = [
    'ñuble',
    'chillañejo',
    'chillañeja',
    'chillán',
    'chillan',
    'chillanejo',
    'chillaneja',
    '#ñuble',
    '#chillán',
    '#chillan',
]

[nuble.tweet_tokens]
must_have = [
    '@nubleonline_',
    '@cronicachillan',
    '@chillanews_cl',
    '@chillanonline',
    '@nubledigital',
    '@radionuble',
]

[tarapaca]
title = 'Región de Tarapacá'
REGION_ID = 1

[tarapaca.user_name]
must_have = ['tarapacá', 'iquique']

[tarapaca.location]
patterns = [
    'iquique',
    'alto hospicio',
    'tarapaca',
    'tarapacá',
    'pozo almonte',
    'el tamarugal',
    'colchane',
    'pica, chile',
    'camiña',
    'huara',
]

[tarapaca.description_token]
must_have = [
    'iquique',
    'iquiqueño',
    'iquiqueña',
    'tarapacá',
    'hospicio',
    '#iquique',
]

[tarapaca.tweet_tokens]
must_have = ['@subderetarapaca']

[tarapaca.domain]
must_have = ['elsoldeiquique.cl']

[tarapaca.account_ids]
known_users = [
    563968996, # redtarapaca
]
